---
- hosts: apigee
  max_fail_percentage: 0
  roles:
    - apigee-bootstrap
    - apigee-base
    - apigee-edge
    - apigee-tls-ms
    - apigee-tls-ui
    - apigee-tls-mp
    - apigee-organization
    - apigee-dev-portal
    - apigee-validate
  vars:
    apigee_topology:
      - dc-1 host01 ms
      - dc-1 host02 ds
      - dc-1 host03 ds
      - dc-1 host04 ds
      - dc-1 host05 rmp
      - dc-1 host06 rmp
      - dc-1 host07 qs
      - dc-1 host08 qs
      - dc-1 host09 ps
      - dc-1 host10 pdb,dp
      - dc-2 host11 ms
      - dc-2 host12 ds
      - dc-2 host13 ds
      - dc-2 host14 ds
      - dc-2 host15 rmp
      - dc-2 host16 rmp
      - dc-2 host17 qs
      - dc-2 host18 qs
      - dc-2 host19 ps
      - dc-2 host20 pdb,dp

    # Set this to false to retain installation files in the temporary directory
    # (default: /tmp/apigee).
    apigee_clean_up: true

    # apigee-base
    apigee_installation_path: /opt
    # Google-hosted Internet repo
    apigee_repository_username: SET_ME
    apigee_repository_password: SET_ME
    # Locally-hosted repo mirror
    #apigee_repository_protocol: http://
    #apigee_repository_address: mirror-address
    #apigee_repository_username: admin
    #apigee_repository_password: admin
    # Tarball stored on the filesystem
    #apigee_repository_protocol: file://
    #apigee_repository_base_path: /path/to/repos

    # apigee-edge
    apigee_admin_email: opdk@apigee.com
    apigee_admin_password: Apigee11
    apigee_ldap_password: Apigee11
    apigee_postgresql_password: Apigee11
    apigee_cassandra_password: Apigee11
    # Path to the license file on the Ansible control host.
    apigee_license_path: SET_ME
    # Leave blank to disable mail.
    apigee_smtp_host:
    apigee_smtp_mail_from: noreply@apigee.com

    # apigee-organization
    apigee_organization_name: apigee
    apigee_environment_name: dev
    apigee_virtual_host_port: 9001
    # Add as many aliases as needed.
    apigee_virtual_host_aliases:
      - SET_ME_1
      - SET_ME_2

    # apigee-dev-portal
    apigee_dp_admin_firstname: Apigee
    apigee_dp_admin_lastname: OPDK
    apigee_dp_admin_username: opdk
    apigee_dp_admin_email: opdk@apigee.com
    apigee_dp_admin_password: Apigee11

    # apigee-tls
    # Set these to use existing keystores.
    #apigee_tls_ms_keystore_src:
    #apigee_tls_ms_keystore_keyalias:
    #apigee_tls_ms_keystore_password:
    #apigee_tls_ui_keystore_src:
    #apigee_tls_ui_keystore_keyalias:
    #apigee_tls_ui_keystore_password:
    #apigee_tls_mp_keystore_src:
    #apigee_tls_mp_keystore_keyalias:
    #apigee_tls_mp_keystore_password:
