---
- block:

  - import_tasks: yum.yml
    tags:
      - yum

  - import_tasks: epel.yml
    when:
      - apigee_install_epel
      - apigee_release in apigee_releases_with_epel
    tags:
      - epel

  become: true
  become_user: root
