---
- name: Set PostgreSQL response file path
  set_fact:
    apigee_pdb_response_path: '{{ apigee_tmp_dir }}/response-pdb.txt'

- name: Set developer portal response file path
  set_fact:
    apigee_dp_response_path: '{{ apigee_tmp_dir }}/response-dp.txt'

- name: Generate PostgreSQL response file
  template:
    src: response-pdb.txt.j2
    dest: '{{ apigee_pdb_response_path }}'
    owner: apigee
    group: apigee
    mode: 0600
  when: ('pdb' in apigee.profiles)

- name: Generate developer portal response file
  template:
    src: response-dp.txt.j2
    dest: '{{ apigee_dp_response_path }}'
    owner: apigee
    group: apigee
    mode: 0600
  when: ('dp' in apigee.profiles)
