---
- name: Setup PostgreSQL master
  command: '{{ apigee_setup_path }} -f {{ apigee_edge_response_path }} -p {{ item }}'
  with_items: '{{ apigee.profiles }}'
  when:
    - item in ('ps', 'sax')
    - ansible_default_ipv4.address == apigee.pg_master

- name: Configure replication access
  lineinfile:
    dest: /opt/apigee/customer/application/postgresql.properties
    regexp: ^conf_pg_hba_replication.connection=.*
    line: '{{ apigee.pg_trust }}'
    create: true
    owner: apigee
    group: apigee
    mode: 0644
  with_items: '{{ apigee.profiles }}'
  when:
    - item in ('ps', 'sax')
    - ansible_default_ipv4.address == apigee.pg_master
    - apigee.pg_standby|length > 1
  register: trust

- name: Restart PostgreSQL master
  command: /opt/apigee/apigee-service/bin/apigee-service apigee-postgresql restart
  when: trust.changed

- name: Setup PostgreSQL standby
  command: '{{ apigee_setup_path }} -f {{ apigee_edge_response_path }} -p {{ item }}'
  with_items: '{{ apigee.profiles }}'
  when:
    - item in ('ps', 'sax')
    - ansible_default_ipv4.address != apigee.pg_master

# Bug workaround
- name: Generate Telegraf configuration files
  command: /opt/apigee/apigee-service/bin/apigee-service apigee-postgresql setup -f {{ apigee_edge_response_path }}
  args:
    removes: /opt/apigee/apigee-postgresql
