---
- name: Set Cassandra limits
  copy:
    src: 99-cassandra.conf
    dest: /etc/security/limits.d/99-cassandra.conf
    owner: root
    group: root
    mode: 0644
  when: apigee_set_limits

- name: Setup Datastores
  shell: sleep {{ apigee.cass_pause }}; {{ apigee_setup_path }} -f {{ apigee_edge_response_path }} -p ds

# Try to change the Cassandra password from the default to the new password. If it fails, that probably means setup was
# already run in the past and the default password is no longer in use. To be sure, set the password to its expected
# current value. That will eliminate a connection error as the cause of the failure.
- block:

  - name: Set Cassandra password
    shell: sleep 5; /opt/apigee/apigee-cassandra/bin/cqlsh {{ ansible_default_ipv4.address }} -u cassandra -p {{ apigee_cassandra_default_password }} -e "ALTER USER cassandra WITH password '{{ apigee_cassandra_password }}';"
    failed_when: no

  - name: Set Cassandra password
    command: /opt/apigee/apigee-cassandra/bin/cqlsh {{ ansible_default_ipv4.address }} -u cassandra -p {{ apigee_cassandra_password }} -e "ALTER USER cassandra WITH password '{{ apigee_cassandra_password }}';"

  when:
    - apigee_cassandra_authentication
    - apigee.cass_pause == 0

- name: Configure Cassandra repair job
  cron:
    name: apigee-nodetool-repair
    job: /opt/apigee/apigee-cassandra/bin/nodetool repair
    user: apigee
    weekday: 0
    hour: 0
    minute: '{{ (apigee.cass_pause / 3) | int }}'
    state: present
