---
apigee_become_user: apigee

# This might need to be set for custom Java installations that don't place
# keytool in a standard bin directory.
apigee_tls_keystore_keytool_path: /usr/bin/keytool

apigee_tls_keystore_type: jks
apigee_tls_keystore_dest: /opt/apigee/customer/keystore.jks
apigee_tls_keystore_validity: 7300

# Set these for an existing keystore.
apigee_tls_keystore_src:
apigee_tls_keystore_keyalias: '{{ ansible_fqdn }}'
apigee_tls_keystore_password: '{{ apigee_admin_password | default("Apigee11") }}'
